HOST: http://api.extremmy.com/

--- eXtremmy API ---

---
    В случае возникновения любой ошибки ожидается application/json 
    обект с полями error (идентификатор), message (сообщение для логов), 
    userMessage (опциональное сообщение для пользователя).
---

-- 
Споты
--

GET /spots/list{?$top,$skip}
> Accept: application/json
> If-Modified-Since: Mon, 3 Jun 2013 00:00:00 GMT
< 304
+++++
< 503
< Content-Type: application/json
{ 
    "error": 401,
    "message": "Unknown error.",
    "userMessage": "Unknown error. Please try again later."
}
+++++
< 200
< Content-Type: application/json
< Last-Modified: Mon, 3 Jun 2013 00:00:00 GMT
[    
    {
        "ID": 1,
        "name": "Orient Jumping",
        "coordinate": [54.069073,-10.340239],
        "url": "http://www.extremmy.com",
        "sports": ["skydiving", "wakeboarding"],
        "rating": 3
    }
]

GET /spots/description/{id}/
> Accept: text/html
> If-Modified-Since: Mon, 3 Jun 2013 00:00:00 GMT
< 304
+++++
< 200
< Content-Type: text/html
<p>
   Several paragraphs in light HTML markup 
</p>

POST /spots/add
> Content-Type: application/json
> Accept: application/json
{ 
    "name": "My new point", 
    "coordinate": [55.990154,37.409945],
    "url": "http://www.extremmy.com",
    "sports": ["skydiving"],
    "rating": 3
}
< 401
< Content-Type: application/json
{ 
    "error": 401,
    "message": "Unauthorized user trying to add spot.",
    "userMessage": "Please sign in."   
}
+++++
< 200
< Content-Type: application/json
{ "ID": 42 }